POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "this is blog5",
  "author": "Name",
  "url": "https://gsuih/fbjehdj/hefgwhjg",
  "likes": 7
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Aleksandr",
  "username": "Aleksandr",
  "password": "55555"
}